# Deployment configuration

repo-name    = "Foundation-CloudWatch2S3"
part-of      = 'foundation'


[[pre-SAM-CloudFormation]]
name         = "INFRA-foo-bar"
template     = 'cloudformation/foo-bar.yaml'
account      = '{admin-account}'
regions      = '{main-region}'

[[pre-SAM-CloudFormation]]
name         = "INFRA-baz-role"
template     = 'cloudformation/baz-role.yaml'
account      = 'ALL'
regions      = '{main-region}'
capabilities = 'CAPABILITY_NAMED_IAM'

[[pre-SAM-CloudFormation]]
name         = "INFRA-quux"
template     = 'cloudformation/quux.yaml'
account      = 'ALL'
regions      = '{all-regions}'


[SAM]
stack-name   = "INFRA-CloudWatch2S3"
profile      = "admin-account"
regions      = '{all-regions}'
